// Dit-Dah-Dash_Refactored/src/js/game/loremIpsumGenerator.js

/**
	* js/game/loremIpsumGenerator.js
	* -------------------------------
	* Utility class for providing Lorem Ipsum text for practice.
	* Provides words from a standard Lorem Ipsum passage, shuffled randomly on initialization.
	*/
export class LoremIpsumGenerator {
    constructor() {
    	 	 	 	 // Standard Lorem Ipsum passage - can be extended if needed
    	 	 	 	 this.loremIpsumText = `
    	 	 	 	 	 	consectetur adipiscing elit. Morbi consequat nisl non elit scelerisque congue. Morbi pharetra augue urna, tristique tempor mi tempus in. Nam posuere vitae sem vitae tincidunt. Quisque venenatis risus in libero aliquam, commodo blandit est porttitor. Etiam sit amet risus et orci eleifend ultrices. Donec quis fermentum metus. Fusce ut lectus tellus. Ut ex velit, dapibus at augue et, pulvinar porta nisi. Ut bibendum viverra erat quis volutpat. Nulla mollis tempus sollicitudin. Aenean pretium ultricies dolor, sed porttitor ex vehicula vitae. In pulvinar sollicitudin tortor a commodo.
                            In iaculis nisl rhoncus accumsan imperdiet. Cras feugiat velit metus, nec porttitor nibh gravida in. Nulla dignissim in lorem eget aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam interdum ultricies gravida. Pellentesque leo urna, faucibus suscipit elementum ut, porta vel velit. Nunc blandit sem lacinia ante dictum semper. Sed ultrices purus non lobortis molestie. Fusce dapibus suscipit lacinia. Suspendisse arcu dui, efficitur non accumsan ut, semper at risus. Mauris blandit, orci et accumsan ultricies, velit odio commodo mi, vel pretium metus leo quis turpis. Donec eleifend tincidunt purus, id sagittis neque pulvinar faucibus. Vestibulum lacinia a lacus non rutrum. Morbi sed felis lacinia risus pharetra mollis hendrerit sit amet orci.
                            Ut sodales ultricies lacinia. Fusce aliquet lorem ac lectus consequat, a hendrerit mauris tristique. Nulla sit amet viverra nulla, ac vehicula urna. Integer pulvinar ligula ac rutrum ullamcorper. Cras posuere risus vel convallis faucibus. Nullam varius sodales magna sit amet ultricies. Donec nibh urna, dignissim a tellus ultrices, mollis vestibulum erat. Mauris euismod non odio non sollicitudin. Sed nunc felis, interdum nec sem a, scelerisque convallis nulla. Donec imperdiet ex enim. Integer ornare vel mi eget blandit. Phasellus in turpis maximus ex pharetra tempus ut sit amet sem. In vel consectetur lacus
                            Cras eleifend enim sed libero hendrerit ultricies. Nam maximus urna nec tortor faucibus, non congue urna aliquam. Nulla posuere vehicula nisl id scelerisque. Nullam id lacus eget lectus ultrices egestas. Maecenas tempus dignissim mi bibendum molestie. Duis luctus ligula ipsum, eget blandit metus fermentum id. Maecenas tempus nisi vitae justo suscipit placerat. Vestibulum lacus nulla, luctus eu purus ut, dictum ornare nisi. In aliquam vestibulum lacinia. Duis nec est varius, aliquet lectus ac, cursus erat.
                            Aenean scelerisque aliquet quam semper dignissim. Nullam sit amet egestas velit, ac scelerisque libero. Phasellus interdum mauris erat, sed faucibus diam tincidunt eu. Aliquam vel ipsum hendrerit, feugiat est vitae, vulputate nulla. Aenean auctor nisi libero, id commodo sapien sodales ut. Vestibulum mollis orci non ex fermentum placerat. Nam consequat, nulla sit amet facilisis aliquet, arcu lectus viverra nisi, eget gravida felis nunc nec risus. Nullam elit sem, semper id ex in, tincidunt tempus mauris. Phasellus mattis libero id imperdiet faucibus. Proin aliquam diam nec lectus elementum consequat. Vestibulum in eros eget diam laoreet ultricies. Ut pulvinar in nibh eu mattis. Etiam velit sem, commodo a urna vitae, mattis condimentum augue. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur vehicula nisi tortor, id finibus risus malesuada et. Vestibulum pulvinar convallis felis sit amet bibendum.
                            Suspendisse ultricies nisl sem, at facilisis lectus tincidunt non. Vestibulum lobortis dapibus mauris eu rutrum. Aliquam quis libero turpis. Pellentesque lobortis velit et ante consectetur faucibus. In vehicula hendrerit nunc, lobortis vehicula tortor lacinia ut. Fusce condimentum nunc at egestas imperdiet. Vivamus ac erat porttitor, ullamcorper purus et, consequat enim. Morbi volutpat ornare scelerisque. Suspendisse tempor condimentum nisl vel finibus.
                            Duis porttitor ante bibendum augue tincidunt facilisis. Morbi vulputate dolor a pharetra mattis. Vivamus id bibendum lacus. Nullam urna tortor, rutrum sit amet ligula et, rutrum fermentum diam. Nullam eleifend ex at lorem mollis viverra. Praesent non consectetur neque, eget dapibus mi. Donec vel quam augue. Mauris quis neque arcu. Donec mattis, odio vel consectetur mollis, eros augue aliquet elit, nec malesuada mauris ligula ac eros. Proin cursus bibendum eleifend. Morbi tincidunt turpis magna, a suscipit arcu vestibulum eget.
                            Nulla fringilla fermentum est pharetra convallis. Nulla finibus magna vel convallis faucibus. In ac eros diam. Mauris quis lorem scelerisque, eleifend libero eget, interdum leo. Praesent nisi odio, eleifend sed libero vel, egestas vehicula dui. Praesent lobortis, felis quis fringilla venenatis, mi ligula lacinia ligula, vitae auctor arcu diam sit amet libero. Sed ornare, leo pulvinar interdum consectetur, est neque imperdiet augue, ac malesuada metus nunc a enim. Duis pretium ligula lorem, nec hendrerit elit tincidunt nec.
                            Nullam suscipit dui eu volutpat hendrerit. Nam aliquet nibh nec ullamcorper tincidunt. In cursus nunc at egestas rhoncus. In fringilla velit nec bibendum ullamcorper. Praesent consequat molestie interdum. Phasellus vel laoreet metus. Nulla commodo condimentum ipsum, vitae porttitor purus imperdiet eu.
                            Duis sit amet turpis eu ligula rutrum dictum. Fusce id ligula ut mi euismod auctor et at urna. Curabitur id rutrum nisl. Vestibulum eu convallis elit, vitae dapibus lectus. Sed ut vestibulum lorem. Vestibulum a ultricies dolor. Praesent pretium ut nunc sed aliquam. Vivamus auctor augue id ligula scelerisque, pulvinar tempus ex elementum. Morbi et mattis ante, ac tincidunt libero. Nam vel tellus quis odio molestie bibendum. Aenean enim elit, accumsan vitae erat et, luctus sollicitudin diam. Quisque cursus tellus eget gravida consequat. Aenean lacinia venenatis nisl et fermentum. Phasellus volutpat mauris sit amet metus suscipit egestas. Phasellus tincidunt, mauris eu iaculis congue, nibh augue commodo ex, eu eleifend turpis nisl eget nisi. Fusce ac mauris at justo auctor pharetra at luctus ex.
                            Nunc eu finibus arcu. Integer ullamcorper ullamcorper nisi. Proin venenatis risus eu metus malesuada, eu pellentesque tortor lobortis. Ut condimentum arcu eu euismod vehicula. In erat velit, pretium et malesuada quis, luctus a neque. Cras varius accumsan congue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam placerat tincidunt purus, in vulputate lectus congue ac. Aliquam nec augue eu nibh gravida facilisis. Nullam efficitur tellus sit amet orci auctor, sit amet elementum libero posuere. Mauris in molestie ligula, sed dictum erat. Nam vulputate mi ac nunc suscipit, vitae posuere nunc facilisis. Nunc et nunc laoreet neque ullamcorper semper id vel ex.
                            Cras luctus vehicula ultrices. Suspendisse consequat in odio ut accumsan. Etiam congue et nibh vitae rhoncus. Donec in suscipit turpis. Ut tempor porttitor lorem a volutpat. Nam sed consequat arcu, sed volutpat metus. Aliquam ut fringilla nibh, quis luctus enim. Etiam nec erat pulvinar, ultricies enim vitae, placerat tellus. Pellentesque in erat at dui molestie vehicula. Sed mollis arcu ac lacus posuere, nec ornare nibh vehicula. Donec convallis nisi quis elit lacinia, in egestas elit interdum. Etiam quis elit eu dui tempus ultricies in porttitor risus. Curabitur leo neque, volutpat nec orci eget, tempor dignissim tellus.
                            Suspendisse commodo nulla scelerisque, elementum sapien ut, congue erat. Quisque luctus dui faucibus urna facilisis tincidunt. Ut vel lobortis turpis, at imperdiet lacus. In pharetra sit amet urna eget convallis. Aliquam semper imperdiet varius. Nullam eleifend urna nunc, id malesuada purus vulputate a. Fusce ac eros sed augue feugiat fermentum volutpat sit amet mi. Suspendisse porta luctus mauris, a porta neque efficitur id.
                            Curabitur nisl velit, lacinia vitae condimentum ut, vestibulum quis elit. Sed rhoncus arcu diam, at accumsan tellus facilisis at. Etiam non elit dui. Ut gravida mauris quis sollicitudin ullamcorper. Sed tincidunt molestie consequat. Phasellus semper dignissim lectus, nec mattis ex facilisis id. Ut at est malesuada, porta sapien maximus, lacinia lacus. Fusce in metus at nibh tempor iaculis facilisis eget libero. Curabitur imperdiet fringilla metus quis fermentum. In massa nisl, dapibus sit amet enim porta, placerat posuere massa. Phasellus vel felis vitae nisi suscipit facilisis viverra vitae ante. Integer rutrum elementum erat, non dictum augue condimentum non. Pellentesque ultrices tortor auctor lectus pulvinar, in porta ligula tempus. Interdum et malesuada fames ac ante ipsum primis in faucibus.
                            In et diam facilisis urna cursus fermentum. Suspendisse dolor tortor, dapibus porttitor aliquam quis, ultrices nec lacus. Fusce mattis placerat velit sed euismod. Donec at felis luctus, varius leo et, mattis enim. Nulla risus dolor, aliquet sed ullamcorper a, consectetur sed enim. Quisque pretium molestie leo vel convallis. Curabitur in commodo odio.
                            In hac habitasse platea dictumst. Cras nisi sapien, congue eget placerat eget, placerat feugiat eros. Etiam sem est, commodo ac vehicula vel, rhoncus in odio. Maecenas commodo, nisl nec mollis pharetra, ipsum sem porttitor dui, et consectetur nisl felis eu nulla. Integer aliquet diam sit amet metus feugiat, eget gravida odio consequat. Donec id massa lectus. Donec efficitur tortor id leo tristique laoreet.
                            Aenean auctor dui ac gravida semper. Proin ut nisl dignissim, venenatis magna nec, vulputate arcu. Praesent feugiat congue ultricies. Integer non blandit nisl, sit amet sodales ex. Curabitur eros ante, ullamcorper vitae auctor at, suscipit scelerisque ligula. Donec ut nibh ac lectus pretium convallis. Nullam eu tortor molestie, sodales metus vitae, pharetra sem. Sed pharetra eu lacus sed euismod.
                            Nulla a blandit nulla, et rhoncus mauris. Sed at lacus elementum, facilisis nulla a, imperdiet ante. Phasellus ornare sem et leo feugiat lobortis. Aenean consectetur tellus eu lectus lacinia, auctor ultrices justo imperdiet. Nam molestie magna eu dui imperdiet, quis vehicula diam efficitur. Aliquam auctor lorem lacus, nec pellentesque felis dignissim et. Phasellus at odio eget diam fermentum rutrum sit amet in risus. Integer luctus blandit erat, et tempor sem ultricies id. Suspendisse a libero dignissim, varius sapien in, congue sapien. Aenean vel nisi lobortis, hendrerit neque non, ullamcorper mi.
                            Nullam massa nunc, consectetur ac nibh sed, laoreet pretium erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum eleifend urna erat, molestie ullamcorper lectus finibus at. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin rutrum pharetra turpis, nec consequat neque pellentesque sit amet. Aenean facilisis ante a quam bibendum, non ornare est convallis. Nullam auctor ante nec consectetur porttitor. Sed in mi non lorem dignissim scelerisque. Aenean tempor ullamcorper risus, eu sollicitudin nisl vestibulum at. Nulla ut mattis lacus. Praesent luctus eros vel risus eleifend, eget lacinia velit convallis. Sed euismod quam varius sapien sagittis, nec luctus libero imperdiet. Phasellus nec tempus magna.
                            Suspendisse hendrerit augue ut aliquet placerat. Nulla ut velit ligula. Aenean facilisis lorem mi, ut aliquet lacus commodo ut. Suspendisse potenti. Phasellus pellentesque purus orci, sit amet consequat augue feugiat quis. Cras scelerisque ante sit amet feugiat elementum. Sed dictum quis nibh at tristique. Etiam vitae placerat mauris, ut ornare enim. Donec sit amet nisi ultrices, auctor ligula ac, sollicitudin enim. Sed vel nisi id sem lacinia faucibus a et velit.
                            Donec fringilla egestas auctor. Ut scelerisque justo elit, a iaculis diam ultricies at. Nulla velit metus, fringilla ut ante sit amet, auctor mattis ligula. Phasellus eu massa a ex placerat lobortis sit amet non nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur ut nibh id urna molestie fermentum eget at lectus. Donec risus justo, faucibus a justo in, molestie efficitur erat. Nullam pretium diam id mauris iaculis, id dictum tellus ultricies.
                            Praesent a auctor nulla, consequat viverra ex. Aenean et dignissim diam, in ultrices dui. Curabitur pellentesque finibus ipsum, non dictum diam placerat a. Fusce eget lectus ac lacus lobortis facilisis. Integer ultrices odio id lorem iaculis auctor. Integer tincidunt mauris sem, ac congue sapien pretium ultricies. Sed pellentesque mauris sit amet dictum pharetra. Praesent tempus sem cursus lacus scelerisque commodo. Etiam tempus commodo nisl consequat ullamcorper. Praesent mattis nunc velit, quis consectetur dui gravida sed. Integer sodales, lectus ac semper tincidunt, sapien lorem posuere nisl, nec congue ipsum massa eget dui. Etiam ipsum diam, suscipit sed elit in, eleifend suscipit neque. Nunc rhoncus nisl dui, sit amet cursus lectus egestas ac. Proin dictum lorem quis urna facilisis, mattis ornare augue consectetur.
                            Vestibulum ut fermentum ante. Proin non libero gravida, ornare nisl vel, mattis arcu. Nulla varius lectus a libero malesuada, aliquam eleifend felis rutrum. Nam sed efficitur lacus, eu congue dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed sed magna eros. Etiam aliquet erat eu eleifend condimentum. Vestibulum id congue nisl. Maecenas at suscipit eros, eget aliquet neque. Morbi a vehicula lectus, eu imperdiet mi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque imperdiet lacus nec libero hendrerit tincidunt. In hac habitasse platea dictumst. Suspendisse ligula risus, iaculis eget ex non, dictum dignissim nulla. Nam mollis consequat quam quis condimentum.
                            Etiam id leo hendrerit, tempus leo ac, dictum ex. Sed ullamcorper magna sapien, a convallis nibh convallis sagittis. Etiam ac auctor turpis. Morbi nec hendrerit lectus. Nunc non dolor at enim tincidunt ornare nec sollicitudin velit. Fusce gravida ultrices est, tristique mollis lectus varius vitae. Integer at felis eget dui pharetra vulputate. Ut in ex eget tellus semper egestas eget vestibulum libero. Praesent congue leo vel tortor posuere dapibus. Phasellus in magna eleifend, mollis nibh sed, ultrices elit.
                            Ut sit amet libero lacinia libero tincidunt cursus at maximus neque. Maecenas aliquet nibh in ligula eleifend, nec rhoncus augue tempus. Maecenas eleifend elementum ligula, at faucibus justo commodo quis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In dapibus rhoncus euismod. Nunc diam eros, faucibus in augue nec, euismod pharetra magna. Praesent consectetur dui nisl, et fringilla leo fringilla vitae. Sed molestie leo eget dolor dapibus vulputate. Donec ut nunc a augue sodales ornare.
                            Cras ultricies tincidunt nisi. Donec egestas dui eget est facilisis, non ultrices nulla pretium. Nunc purus ante, vulputate non metus et, gravida bibendum nisi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque ac leo vulputate, aliquet ligula sed, accumsan nunc. Cras mollis sapien nec rutrum consectetur. Mauris vitae magna metus. Pellentesque mi dolor, sodales eu odio at, venenatis ultrices tortor. Nulla pretium non orci in iaculis.
                            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus lacus odio, interdum at interdum eu, accumsan in ligula. Nullam ultrices elit et cursus cursus. Fusce consectetur quam vitae augue volutpat, eget vulputate dui ultricies. Curabitur at tortor a nisi commodo molestie. In lectus massa, iaculis sit amet purus in, blandit rutrum magna. Donec est est, ullamcorper vitae auctor ac, accumsan at magna. Integer tincidunt varius felis sit amet lobortis. Aliquam commodo ante sed diam sollicitudin, nec convallis orci viverra. Donec ut nunc feugiat, dignissim odio ac, congue urna. Vivamus placerat feugiat massa, sit amet pellentesque nisl rutrum eu. Donec posuere rutrum velit, in sodales dui iaculis nec. Curabitur a blandit mi.
                            Praesent non mauris tempor, mollis libero et, interdum nisl. Quisque non finibus risus, ut egestas elit. Aenean vitae diam sit amet eros egestas feugiat et eu nunc. Nullam sed posuere erat. Donec varius, odio quis gravida faucibus, enim dolor faucibus dolor, sit amet pretium velit lacus sed dolor. Sed congue, diam id venenatis aliquet, nunc diam finibus quam, sed rutrum enim nisl et massa. Donec tempus ipsum quis ante luctus, vitae pulvinar dui dictum. Phasellus nisl libero, commodo sit amet nisl vitae, suscipit elementum quam. Phasellus sed metus eget dui sodales efficitur. Nullam nec ex eget ante pretium bibendum. Curabitur eget justo sed libero sodales tincidunt eget ac odio. Donec lobortis efficitur felis sed faucibus. Duis nibh orci, congue nec nunc eu, vehicula ullamcorper urna.
                            Curabitur eleifend vehicula ex nec accumsan. Phasellus porttitor risus turpis. Ut scelerisque in diam eget viverra. Nullam est tellus, vehicula eu neque eu, pretium hendrerit mauris. Pellentesque odio dolor, ultricies at dignissim in, consectetur aliquet sapien. Nam semper ligula eu erat tincidunt, a imperdiet turpis blandit. Donec velit massa, pharetra et tincidunt ac, ultrices sed metus. Donec aliquet cursus tellus.
                            Vestibulum tempor pellentesque risus, in auctor justo ornare rutrum. Sed id quam eget risus euismod finibus. Vestibulum nec consequat risus. Nam congue euismod turpis, et volutpat tortor dignissim in. Praesent tellus odio, ullamcorper a turpis in, tincidunt eleifend enim. Aliquam id vulputate sapien. Aliquam porttitor sodales magna vel semper. Phasellus at vehicula sem. Nullam sed convallis ex. Phasellus rhoncus auctor sagittis. Praesent odio ex, sodales eget odio ac, vestibulum accumsan neque. Donec feugiat leo sed vestibulum blandit. Etiam eu bibendum sapien, nec laoreet diam. Etiam mi nisl, malesuada id magna non, condimentum interdum orci.
                            Aliquam consectetur pellentesque lobortis. Nulla hendrerit, tellus ut rutrum semper, tortor justo rhoncus ex, ac aliquam odio nulla sed dui. Fusce vitae euismod leo, eget condimentum libero. Suspendisse potenti. Nulla non nulla leo. Ut placerat nunc ac quam interdum consectetur. In hac habitasse platea dictumst. Donec tellus mi, finibus congue egestas quis, sodales at nulla. Sed tristique orci a dignissim pulvinar. Praesent at fringilla lectus, eu laoreet justo.
                            Vivamus non sem et lectus aliquet condimentum ac in lacus. Praesent a ornare sem. Mauris et congue orci, id cursus neque. Morbi varius suscipit blandit. Pellentesque sollicitudin pulvinar massa, nec ultrices turpis congue et. Donec porta, arcu ac vehicula lobortis, purus neque convallis arcu, non pulvinar leo elit ac eros. Nulla dictum laoreet ipsum a tincidunt. Donec vehicula purus eget est ullamcorper, id hendrerit lectus porttitor. Curabitur quis sapien sem. Pellentesque eget urna at orci egestas fermentum nec eget dui.
                            Ut viverra eget mi id ultrices. Maecenas vitae felis sem. Vivamus sed ante eleifend, interdum turpis vitae, cursus tortor. In eget tortor malesuada, elementum odio in, dictum mi. Integer in iaculis erat. Vestibulum scelerisque arcu magna. Donec augue massa, malesuada vel mauris at, finibus dapibus elit. Duis elit magna, hendrerit vel semper nec, vehicula quis risus. Aliquam leo tellus, consectetur eu suscipit eu, porta eget tortor. Curabitur non felis sit amet ipsum tempor accumsan vitae aliquam enim. Aliquam id magna libero. Nam tellus tortor, sodales vel ipsum eget, porta ornare arcu. Cras accumsan augue sit amet dui tincidunt ornare.
                            Integer nec egestas mi. Praesent id mattis lectus. Etiam pharetra eros mauris. Donec quis ullamcorper turpis. In efficitur tempor leo, vel ultricies augue sodales eu. Vestibulum eu velit sit amet turpis eleifend gravida a eget orci. Aliquam rutrum massa metus, et dapibus nisl sodales a.
                            Aenean consectetur est leo. Nullam sed erat sed tortor iaculis gravida a non quam. Duis vel rhoncus tellus, quis aliquam est. Nunc laoreet libero dolor, quis auctor erat iaculis efficitur. Sed sed nulla non velit ultrices vestibulum nec id ante. Quisque tincidunt orci at vulputate pellentesque. Vivamus efficitur justo libero, quis maximus nulla posuere ut. Curabitur condimentum aliquam sapien, porttitor consectetur diam finibus ut. In pretium orci non egestas tristique.
                            Suspendisse potenti. Cras sodales congue mi vitae sollicitudin. Ut sed ultricies ante. Nulla vitae ex et dolor malesuada laoreet. Vivamus at mauris tristique, consectetur lorem ut, dignissim eros. Nunc euismod mauris eu dolor tristique aliquam. Mauris in dictum sapien. In lobortis quis neque eu ullamcorper. Integer accumsan arcu quam, eu commodo velit blandit nec. Cras lacus purus, molestie ut justo at, iaculis interdum eros. Vestibulum mattis quam ut lectus faucibus, at gravida elit efficitur. Proin ac lorem quis ante faucibus rhoncus. Cras laoreet maximus felis, sed auctor erat venenatis faucibus.
                            Cras leo nisi, vehicula rhoncus tincidunt id, cursus nec elit. Nam leo ipsum, laoreet sed arcu eget, molestie faucibus libero. Cras sem nunc, egestas in viverra id, finibus vitae justo. Nullam convallis vel dui id rutrum. Donec bibendum, arcu at rhoncus efficitur, urna velit tincidunt ligula, sed lacinia mi risus et felis. Mauris volutpat nunc sit amet magna hendrerit fermentum. Vivamus ipsum arcu, ultricies vitae blandit tincidunt, dictum non justo. Cras tristique risus a nibh pellentesque egestas.
                            Duis mollis vulputate vulputate. Etiam elementum tellus purus, sit amet vestibulum nibh lobortis et. Morbi fermentum molestie feugiat. In arcu justo, laoreet id tellus non, hendrerit suscipit tortor. Sed euismod, neque sed condimentum iaculis, sapien turpis consequat diam, vitae vehicula nulla ante ut elit. Sed a accumsan neque. Nam in imperdiet lacus. Curabitur in risus sed nulla pharetra euismod sit amet ac purus. Donec accumsan sapien eros, sollicitudin tincidunt lorem tristique vel. Aenean rhoncus nunc nec risus sodales bibendum. Curabitur pellentesque diam in diam molestie, auctor viverra tortor tincidunt. Proin dapibus, justo pellentesque bibendum vulputate, purus magna vehicula velit, a luctus justo augue dictum sapien. Vestibulum blandit non neque sit amet feugiat. Donec enim quam, congue vitae odio vel, bibendum tristique dui.
                            Morbi pulvinar tortor metus, id aliquam velit egestas eu. Fusce pharetra tempor ex in dignissim. Ut in diam nibh. Vestibulum in velit vel nulla auctor scelerisque at sit amet purus. Sed suscipit vestibulum est, non consectetur velit fringilla eu. Maecenas ultrices feugiat sagittis. Sed consequat eu elit sed convallis. Mauris convallis imperdiet neque at vestibulum. Etiam sagittis volutpat gravida.
                            Curabitur ullamcorper nec justo a rutrum. Vestibulum dui neque, elementum at convallis vitae, sagittis eget augue. In hac habitasse platea dictumst. Cras fringilla enim felis, sed aliquam augue feugiat sit amet. Maecenas id lacinia mi, quis facilisis dui. Aenean in ligula pretium magna lobortis lacinia. Etiam nec pharetra sem. Fusce a dolor nulla.
                            Nullam id leo sodales turpis vulputate vestibulum. Quisque lacus felis, laoreet quis varius sed, accumsan in diam. Duis ornare lacus et fermentum ultricies. Pellentesque varius risus sed hendrerit varius. Curabitur quis iaculis neque. Aliquam ullamcorper lobortis nulla vitae vulputate. Nulla facilisi. Maecenas maximus, nisl sit amet suscipit imperdiet, leo urna semper ante, nec cursus diam orci nec magna. Aenean euismod lorem ac est mattis ultricies. Donec id diam eu ligula maximus faucibus. Donec ac nisi orci. Nam tristique, risus vitae semper tincidunt, ipsum eros varius quam, at pretium ante nunc nec dui.
                            Morbi ac eros vitae tortor ornare sollicitudin et ut lorem. Proin ornare gravida velit non scelerisque. Nulla facilisi. Mauris vel pulvinar dui. Maecenas cursus feugiat ultricies. Vivamus quis volutpat nibh, et ullamcorper urna. Aliquam a neque quis arcu congue vehicula molestie non diam. Ut vulputate felis a fringilla ullamcorper. Praesent id dolor lacinia, ornare est id, fringilla magna. Sed id sapien at augue aliquet aliquet. Nulla facilisi. Proin semper, elit nec placerat scelerisque, nulla nulla cursus eros, ac posuere eros justo non diam. Vivamus convallis suscipit nulla eget lobortis.
                            Curabitur aliquam gravida ante, vitae pellentesque sapien accumsan vitae. Aenean nec odio elit. Maecenas mattis congue elementum. Etiam sed fermentum quam, id bibendum purus. Proin at pellentesque augue. Cras porttitor felis in fermentum cursus. Curabitur finibus vel massa sit amet ultricies. Proin vitae dui porttitor, iaculis felis at, blandit odio. Morbi sed arcu et dui interdum ullamcorper. Nullam nec arcu eget ipsum euismod commodo. Cras dictum ante eget mi lobortis scelerisque. Proin fermentum ligula erat, eu pellentesque ligula aliquet ac. Vivamus nec erat erat.
                            Nulla nisl neque, tempus eu efficitur non, dapibus sed tortor. Duis mollis est nulla, vitae ultrices purus laoreet vitae. Phasellus commodo ornare nisl vel hendrerit. Duis tortor nisi, malesuada sed augue vitae, laoreet facilisis nibh. Duis tempor turpis quis nisi semper, vel lobortis lacus malesuada. Nunc sit amet mollis turpis. Suspendisse finibus ullamcorper turpis, quis dapibus turpis. Curabitur tempor ipsum in pulvinar vulputate.
                            Phasellus arcu lectus, rhoncus eget tincidunt non, aliquam id massa. Proin tincidunt consectetur vehicula. Donec id odio tempus, gravida risus at, mollis arcu. Duis tempus arcu at vulputate feugiat. Suspendisse pretium metus in cursus tempor. Nulla in eros ut leo condimentum lobortis et et lectus. Sed a sem et tellus suscipit tristique at nec ipsum. Etiam eget bibendum nulla, eget luctus ligula. Quisque eu est tellus. Proin dapibus velit augue, eu rhoncus urna hendrerit sit amet. Nullam consectetur blandit lorem vel feugiat. Morbi sagittis dolor semper tincidunt commodo. Fusce iaculis ex at mi bibendum, ac aliquam libero condimentum. Sed pharetra, lectus in faucibus malesuada, turpis neque venenatis erat, vitae tempor ipsum dolor sit amet ante.
                            Cras finibus dignissim molestie. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean lacinia facilisis elementum. Curabitur in nisi nisl. Proin euismod velit id magna mollis convallis. Morbi sed imperdiet neque. Etiam tempus iaculis accumsan. Nunc viverra massa at efficitur ultrices. Cras a purus suscipit, laoreet ligula et, sollicitudin dui. Vivamus bibendum turpis eget risus viverra pulvinar.
                            Fusce elementum lobortis ligula. Phasellus aliquet orci in egestas ullamcorper. Pellentesque augue tellus, commodo nec varius ac, viverra eget sem. Nam non finibus magna, eget rhoncus diam. Morbi eleifend, justo eu facilisis efficitur, mauris nibh mollis mi, in tempor turpis turpis nec diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pretium lacinia eros eget aliquet.
                            Quisque eu posuere diam. Etiam in semper augue. Fusce ultrices, metus a mollis tincidunt, dui quam tincidunt quam, a gravida ex metus vel tellus. Aenean et dolor ac ipsum scelerisque lobortis et ac leo. Phasellus elementum et metus quis fringilla. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed et turpis leo.
                            Praesent neque ipsum, bibendum id imperdiet vitae, posuere vitae lacus. Aenean pretium, ante non lobortis pretium, ligula augue iaculis augue, non eleifend diam sapien id lorem. Praesent ac dictum massa. Pellentesque pulvinar blandit nulla, id bibendum quam pharetra id. Donec condimentum elit quis velit congue porta et a orci. Integer justo nisi, hendrerit ac quam ut, molestie egestas lectus. Aliquam vulputate, dolor id venenatis faucibus, tellus elit posuere purus, eu cursus nulla lectus eget odio. Maecenas auctor massa est, in interdum dolor malesuada sed. Vivamus quam turpis, vehicula sit amet bibendum quis, ornare vitae sapien. Praesent sagittis, dui a molestie rhoncus, augue ipsum sodales odio, eget hendrerit lorem enim in ligula. Vestibulum tincidunt velit et varius tincidunt.
                            Ut commodo nisl eget risus volutpat mollis. Sed molestie nisl tortor, non tincidunt odio placerat at. Aliquam erat volutpat. Aliquam in posuere purus, eu tincidunt nulla. Phasellus rutrum magna non mi auctor hendrerit. Sed eros magna, rutrum et ante id, bibendum posuere justo. Donec congue mauris et ante maximus, nec porta sapien venenatis. Sed libero nisl, eleifend ut nulla quis, convallis mollis diam. Praesent tempor, nibh quis scelerisque tempus, augue augue pharetra arcu, nec malesuada ante odio eget enim. Vivamus blandit lectus velit, eu aliquam felis tempor ut.
                            Morbi tellus diam, scelerisque ac vehicula eget, finibus id nulla. Sed tincidunt pulvinar malesuada. In porta nec nulla et iaculis. Etiam placerat bibendum mi, eu aliquet odio placerat sit amet. Ut tempor faucibus sem, sed vehicula eros commodo id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Quisque id enim purus. Sed at ultrices arcu. Ut molestie eu dui nec gravida. Proin commodo tempus ullamcorper. Sed vel nibh pharetra, sodales massa ut, malesuada ex. Praesent tincidunt interdum diam non ultrices. Praesent mi nunc, efficitur et vulputate dapibus, suscipit eu purus.
                            Nam pretium, quam a feugiat vehicula, enim sem egestas ante, at tincidunt diam neque sit amet leo. Nunc id aliquet velit. Cras sit amet est magna. Integer eleifend massa nisi, nec accumsan neque sollicitudin sit amet. Nunc fermentum purus quis erat sagittis, ac placerat felis accumsan. Cras vehicula erat volutpat neque ultrices, vitae porttitor felis ornare. Donec vel imperdiet libero. Aliquam erat volutpat. Fusce ligula justo, dictum at velit non, lobortis semper nunc. Cras euismod velit quis lorem mollis accumsan. Proin pellentesque feugiat volutpat. Sed iaculis mi mollis dapibus euismod. Curabitur finibus turpis sed massa pulvinar mattis. Sed odio ante, aliquet at faucibus sed, maximus non lorem.
                            Phasellus ullamcorper leo est, ac efficitur elit accumsan quis. Donec mattis eget metus quis faucibus. Nulla leo dolor, porttitor a luctus sed, convallis nec nulla. Aliquam nec metus est. Nullam fringilla porta lorem blandit elementum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut vehicula ullamcorper justo, non aliquet urna fringilla nec. Vestibulum auctor erat at lacus ullamcorper vehicula. Vestibulum vitae consectetur nunc. Sed ornare erat ac dui fermentum scelerisque.
                            Quisque purus urna, dignissim varius risus id, scelerisque dapibus eros. Maecenas mattis, lacus a porttitor rhoncus, elit sem fermentum leo, in ultrices urna ex vitae leo. Integer id bibendum velit. Donec vitae leo ullamcorper, molestie ante tincidunt, dictum eros. Etiam egestas urna malesuada tincidunt laoreet. Sed eget condimentum nisi, in euismod tortor. In hac habitasse platea dictumst. Integer nec augue elit. Phasellus rutrum ligula a justo accumsan porttitor. Sed eu rhoncus lacus. Aenean molestie justo non erat porta, id varius orci placerat. Quisque porta tincidunt risus, at pretium lorem euismod et. Nullam eget elit sed dolor ultrices iaculis ut vitae metus.
                            Maecenas venenatis dui vulputate dui gravida, ut feugiat dui dapibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam cursus iaculis mi ut sollicitudin. Mauris pulvinar lectus ut justo consequat fringilla. Duis eros justo, lobortis nec pharetra vitae, vulputate viverra turpis. Sed maximus porttitor nisl vitae imperdiet. Sed rutrum nibh eget mattis interdum. Integer non fringilla libero, nec sagittis metus. Nulla facilisi. Integer viverra turpis vitae efficitur lacinia. Vivamus aliquam ultricies convallis.
                            Pellentesque cursus, mi a ultricies pulvinar, tortor metus elementum est, sed porttitor nisi lacus eu neque. Phasellus convallis neque sit amet facilisis imperdiet. Pellentesque ac pulvinar ipsum. Duis vitae posuere nibh. Ut fermentum vitae tortor sed dictum. Suspendisse eget malesuada sapien. Duis id dolor tristique, ultricies enim gravida, interdum tellus. Sed sollicitudin, arcu ut vehicula semper, dolor nibh tempor magna, sit amet sagittis ex est id lorem. Cras mauris odio, venenatis quis nibh nec, vestibulum pulvinar elit. Vestibulum tempus metus eget dolor viverra mollis. Praesent vestibulum dictum diam, id egestas nulla feugiat ut. Praesent a ex lorem.
                            In et pharetra ante. Quisque auctor cursus erat, et fringilla ante aliquet id. Vivamus nisi libero, sodales eu mi ut, mattis pulvinar magna. Phasellus scelerisque justo a massa auctor dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse potenti. Donec porttitor pretium libero eu ornare. Nulla pharetra euismod rutrum.
                            Donec quis lacus in eros faucibus condimentum eu at justo. Praesent eleifend sapien nisl, quis feugiat nisi laoreet id. Nulla nec efficitur erat. Curabitur tristique vehicula sapien dictum vehicula. Etiam leo massa, porta non sollicitudin vitae, dapibus nec nunc. Nam ante ipsum, pellentesque non lacus vel, pharetra rhoncus augue. Fusce feugiat ultrices venenatis. Suspendisse sit amet varius lectus. Nulla sed hendrerit nisl. Sed tincidunt malesuada dui, sit amet euismod magna. Sed vel maximus justo, ac vulputate ante. Nullam vel felis luctus, fermentum ante vel, semper lacus. Integer sodales augue vitae neque gravida, in auctor mauris ultricies. Nullam aliquam rutrum accumsan. Integer in vestibulum nisl, a laoreet sapien. Aenean bibendum, nisi et ullamcorper placerat, orci purus elementum orci, quis posuere neque mauris lobortis leo.
                            Cras blandit ultricies dui, eget consectetur enim tempus at. Morbi sodales egestas arcu. Nullam condimentum justo mollis, aliquam neque id, pulvinar elit. Donec at erat congue, malesuada justo non, rutrum diam. Suspendisse imperdiet, felis sed lobortis congue, augue eros mollis dolor.`;
                            
    	 	 	 	 // Process the text into an array of words (uppercase, no punctuation)
    	 	 	 	 this.wordList = this.loremIpsumText
    	 	 	 	 	 	 .trim() // Remove leading/trailing whitespace
    	 	 	 	 	 	 .toUpperCase() // Convert to uppercase
    	 	 	 	 	 	 .replace(/[.,?]/g, '') // Remove common punctuation
    	 	 	 	 	 	 .split(/\s+/); // Split into words by whitespace
    
    	 	 	 	 if (!this.wordList || this.wordList.length === 0) {
    	 	 	 	 	 	 console.error("LoremIpsumGenerator: Failed to process Lorem Ipsum text into words.");
    	 	 	 	 	 	 this.wordList = ["LOREM", "IPSUM", "DOLOR"]; // Basic fallback
    	 	 	 	 }
    
            // --- NEW FEATURE: Shuffle the word list ---
            // Fisher-Yates (Knuth) Shuffle Algorithm
            for (let i = this.wordList.length - 1; i > 0; i--) {
                const j = Math.floor(Math.random() * (i + 1));
                // Swap elements using array destructuring
                [this.wordList[i], this.wordList[j]] = [this.wordList[j], this.wordList[i]];
            }
            // --- End of Shuffle Feature ---
    
    	 	 	 	 this.currentIndex = 0; // Track position in the *shuffled* word list for sequential generation
    
    	 	 	 	 console.log("LoremIpsumGenerator Initialized with shuffled word list."); // Updated log message
    	 	 }
    
    	 	 /**
    	 	 	* Generates a specified number of words sequentially from the *shuffled* Lorem Ipsum word list.
    	 	 	* Wraps around to the beginning if the end of the list is reached.
    	 	 	* @param {number} count - The number of words to generate.
    	 	 	* @returns {Array<string>} An array of generated word strings.
    	 	 	*/
    	 	 generateWords(count) {
    	 	 	 	 if (count <= 0 || this.wordList.length === 0) {
    	 	 	 	 	 	 return [];
    	 	 	 	 }
    
    	 	 	 	 const words = [];
    	 	 	 	 for (let i = 0; i < count; i++) {
    	 	 	 	 	 	 words.push(this.wordList[this.currentIndex]);
    	 	 	 	 	 	 this.currentIndex = (this.currentIndex + 1) % this.wordList.length; // Move to next index and wrap around
    	 	 	 	 }
    	 	 	 	 return words;
    	 	 }
    
    	 	 /**
    	 	 	* Resets the internal index to start generating words from the beginning of the *shuffled* list.
         * Note: This does NOT reshuffle the list. To get a new shuffle, create a new instance.
    	 	 	*/
    	 	 reset() {
    	 	 	 	 this.currentIndex = 0;
    	 	 }
    
        /**
         * Optionally allows re-shuffling the existing word list and resetting the index.
         */
        reshuffle() {
            // Fisher-Yates (Knuth) Shuffle Algorithm
            for (let i = this.wordList.length - 1; i > 0; i--) {
                const j = Math.floor(Math.random() * (i + 1));
                [this.wordList[i], this.wordList[j]] = [this.wordList[j], this.wordList[i]];
            }
            this.reset(); // Reset index after reshuffling
            console.log("LoremIpsumGenerator word list reshuffled.");
        }
    }
    
    // Example Usage:
    // const generator = new LoremIpsumGenerator();
    // const tenWords = generator.generateWords(10);
    // console.log(tenWords.join(' ')); // Output: A sequence of 10 random words from the list
    // const nextFive = generator.generateWords(5);
    // console.log(nextFive.join(' ')); // Output: The next 5 words in the shuffled sequence
    // generator.reshuffle();
    // const tenNewWords = generator.generateWords(10);
    // console.log(tenNewWords.join(' ')); // Output: A new sequence of 10 random words